# UI settings
window.width=596
window.height=842
background.colour=0.0,0.0,0.0
text.font=res/upheavtt.ttf
text.size=24
text.colour=255,255,255
wave.text=Wave
wave.pos=435,48
score.text=Score
score.pos=420,78
playerLives.image=res/playerLife.png
playerLives.startPosition=48,48
playerLives.gap=50

# Player settings
player.image=res/playerSpaceship.png
player.initialLives=3
player.posY=700
player.speed=3
player.shootCooldown=60
projectile.movementSpeed=3
projectile.image=res/playerProjectile.png

# Enemy settings
enemy.image=res/enemy.png
enemy.0.arrivalTime=180
enemy.0.movementSpeed=2
enemy.0.posX=200
enemy.1.arrivalTime=180
enemy.1.movementSpeed=4
enemy.1.posX=396
enemy.2.arrivalTime=360
enemy.2.movementSpeed=2
enemy.2.posX=200
enemy.3.arrivalTime=360
enemy.3.movementSpeed=4
enemy.3.posX=396
enemy.4.arrivalTime=540
enemy.4.movementSpeed=2
enemy.4.posX=200
enemy.5.arrivalTime=540
enemy.5.movementSpeed=4
enemy.5.posX=396
enemy.6.arrivalTime=720
enemy.6.movementSpeed=2
enemy.6.posX=200
enemy.7.arrivalTime=720
enemy.7.movementSpeed=4
enemy.7.posX=396
enemy.8.arrivalTime=900
enemy.8.movementSpeed=2
enemy.8.posX=200
enemy.9.arrivalTime=900
enemy.9.movementSpeed=4
enemy.9.posX=396

# Explosion settings
explosion.duration=30
explosion.image=res/explosion.png

# Pause screen settings
pausedTitle.text=GAME PAUSED
pausedTitle.size=48
pausedTitle.posY=300
controlsList.text=A/D KEYS TO MOVE,SPACEBAR TO SHOOT,G TO INCREASE SPEED,F TO DECREASE SPEED,I TO ENABLE INVINCIBLE MODE,ESC TO PAUSE/UNPAUSE,R TO RESTART GAME
controlsList.startPosY=350
controlsList.rowGap=30
timescale.text=SPEED X
timescale.pos=450,800