# UI settings
window.width=596
window.height=842
background.colour=0.0,0.0,0.0
text.font=res/upheavtt.ttf
text.size=24
text.colour=255.0,255.0,255.0
wave.text=Wave
wave.pos=435,48
playerLives.image=res/playerLife.png
playerLives.startPosition=48,48
playerLives.gap=50

# Player settings
player.image=res/playerSpaceship.png
player.initialLives=3
player.posY=700
player.speed=3
player.shootCooldown=60
projectile.movementSpeed=3
projectile.image=res/playerProjectile.png
invincibility.image=res/invincible.png
player.hitInvincibilityTime=60

# Score settings
score.destroyedEnemy.regular=100
score.destroyedEnemy.strafing=200
score.destroyedEnemy.shooting=300
score.gotHit=1000
score.gotPowerup=500
score.hitProjectile=50
score.pos=420,78
score.text=Score
score.waveCompleted=1000

# Enemy settings
enemy.regular.image=res/regularEnemy.png
enemy.strafing.image=res/strafingEnemy.png
enemy.shooting.image=res/shootingEnemy.png
enemy.shooting.firingRate=120
enemyProjectile.image=res/enemyProjectile.png
enemyProjectile.movementSpeed=6

# Powerup settings
powerup.shield.duration=300
powerup.shield.image=res/shieldPowerup.png
powerup.shield.movementSpeed=2
powerup.life.image=res/lifePowerup.png
powerup.life.movementSpeed=4
powerup.cooldown.duration=120
powerup.cooldown.image=res/cooldownPowerup.png
powerup.cooldown.movementSpeed=5
powerup.engine.duration=600
powerup.engine.image=res/enginePowerup.png
powerup.engine.movementSpeed=3

# Wave settings
wave.1.enemy.0.arrivalTime=120
wave.1.enemy.0.movementSpeed=2
wave.1.enemy.0.posX=118
wave.1.enemy.0.type=regular
wave.1.enemy.1.arrivalTime=168
wave.1.enemy.1.movementSpeed=4
wave.1.enemy.1.posX=248
wave.1.enemy.1.type=regular
wave.1.enemy.2.arrivalTime=168
wave.1.enemy.2.movementSpeed=3
wave.1.enemy.2.posX=405
wave.1.enemy.2.type=regular
wave.1.enemy.3.arrivalTime=225
wave.1.enemy.3.movementSpeed=5
wave.1.enemy.3.posX=512
wave.1.enemy.3.type=regular
wave.1.enemy.4.arrivalTime=270
wave.1.enemy.4.movementSpeed=1
wave.1.enemy.4.posX=174
wave.1.enemy.4.type=regular
wave.1.enemy.5.arrivalTime=270
wave.1.enemy.5.movementSpeed=6
wave.1.enemy.5.posX=318
wave.1.enemy.5.type=regular
wave.1.enemy.6.arrivalTime=270
wave.1.enemy.6.movementSpeed=2
wave.1.enemy.6.posX=462
wave.1.enemy.6.type=regular
wave.1.enemy.7.arrivalTime=324
wave.1.enemy.7.movementSpeed=4
wave.1.enemy.7.posX=91
wave.1.enemy.7.type=regular
wave.1.enemy.8.arrivalTime=378
wave.1.enemy.8.movementSpeed=3
wave.1.enemy.8.posX=372
wave.1.enemy.8.type=regular
wave.1.powerup.0.arrivalTime=210
wave.1.powerup.0.posX=280
wave.1.powerup.0.type=shield
wave.1.powerup.1.arrivalTime=420
wave.1.powerup.1.posX=435
wave.1.powerup.1.type=cooldown

wave.2.enemy.0.arrivalTime=60
wave.2.enemy.0.movementSpeed=5
wave.2.enemy.0.posX=96
wave.2.enemy.0.type=strafing
wave.2.enemy.1.arrivalTime=105
wave.2.enemy.1.movementSpeed=3
wave.2.enemy.1.posX=221
wave.2.enemy.1.type=strafing
wave.2.enemy.2.arrivalTime=105
wave.2.enemy.2.movementSpeed=6
wave.2.enemy.2.posX=384
wave.2.enemy.2.type=strafing
wave.2.enemy.3.arrivalTime=156
wave.2.enemy.3.movementSpeed=2
wave.2.enemy.3.posX=511
wave.2.enemy.3.type=strafing
wave.2.enemy.4.arrivalTime=210
wave.2.enemy.4.movementSpeed=4
wave.2.enemy.4.posX=143
wave.2.enemy.4.type=strafing
wave.2.enemy.5.arrivalTime=210
wave.2.enemy.5.movementSpeed=1
wave.2.enemy.5.posX=302
wave.2.enemy.5.type=strafing
wave.2.enemy.6.arrivalTime=258
wave.2.enemy.6.movementSpeed=5
wave.2.enemy.6.posX=453
wave.2.enemy.6.type=strafing
wave.2.enemy.7.arrivalTime=315
wave.2.enemy.7.movementSpeed=6
wave.2.enemy.7.posX=183
wave.2.enemy.7.type=strafing
wave.2.enemy.8.arrivalTime=315
wave.2.enemy.8.movementSpeed=2
wave.2.enemy.8.posX=347
wave.2.enemy.8.type=strafing
wave.2.enemy.9.arrivalTime=315
wave.2.enemy.9.movementSpeed=4
wave.2.enemy.9.posX=508
wave.2.enemy.9.type=strafing
wave.2.enemy.10.arrivalTime=372
wave.2.enemy.10.movementSpeed=3
wave.2.enemy.10.posX=259
wave.2.enemy.10.type=strafing
wave.2.powerup.0.arrivalTime=180
wave.2.powerup.0.posX=118
wave.2.powerup.0.type=engine
wave.2.powerup.1.arrivalTime=390
wave.2.powerup.1.posX=482
wave.2.powerup.1.type=life

wave.3.enemy.0.arrivalTime=60
wave.3.enemy.0.movementSpeed=1
wave.3.enemy.0.posX=300
wave.3.enemy.0.type=shooting
wave.3.enemy.1.arrivalTime=96
wave.3.enemy.1.movementSpeed=3
wave.3.enemy.1.posX=136
wave.3.enemy.1.type=shooting
wave.3.enemy.2.arrivalTime=96
wave.3.enemy.2.movementSpeed=4
wave.3.enemy.2.posX=462
wave.3.enemy.2.type=shooting
wave.3.enemy.3.arrivalTime=153
wave.3.enemy.3.movementSpeed=2
wave.3.enemy.3.posX=217
wave.3.enemy.3.type=shooting
wave.3.enemy.4.arrivalTime=198
wave.3.enemy.4.movementSpeed=6
wave.3.enemy.4.posX=394
wave.3.enemy.4.type=shooting
wave.3.enemy.5.arrivalTime=198
wave.3.enemy.5.movementSpeed=5
wave.3.enemy.5.posX=512
wave.3.enemy.5.type=shooting
wave.3.enemy.6.arrivalTime=249
wave.3.enemy.6.movementSpeed=2
wave.3.enemy.6.posX=88
wave.3.enemy.6.type=shooting
wave.3.enemy.7.arrivalTime=303
wave.3.enemy.7.movementSpeed=4
wave.3.enemy.7.posX=276
wave.3.enemy.7.type=shooting
wave.3.powerup.0.arrivalTime=150
wave.3.powerup.0.posX=352
wave.3.powerup.0.type=cooldown
wave.3.powerup.1.arrivalTime=330
wave.3.powerup.1.posX=167
wave.3.powerup.1.type=shield

wave.4.enemy.0.arrivalTime=60
wave.4.enemy.0.movementSpeed=4
wave.4.enemy.0.posX=108
wave.4.enemy.0.type=regular
wave.4.enemy.1.arrivalTime=60
wave.4.enemy.1.movementSpeed=6
wave.4.enemy.1.posX=300
wave.4.enemy.1.type=strafing
wave.4.enemy.2.arrivalTime=60
wave.4.enemy.2.movementSpeed=2
wave.4.enemy.2.posX=492
wave.4.enemy.2.type=shooting
wave.4.enemy.3.arrivalTime=111
wave.4.enemy.3.movementSpeed=5
wave.4.enemy.3.posX=184
wave.4.enemy.3.type=strafing
wave.4.enemy.4.arrivalTime=150
wave.4.enemy.4.movementSpeed=3
wave.4.enemy.4.posX=415
wave.4.enemy.4.type=regular
wave.4.enemy.5.arrivalTime=150
wave.4.enemy.5.movementSpeed=1
wave.4.enemy.5.posX=248
wave.4.enemy.5.type=shooting
wave.4.enemy.6.arrivalTime=201
wave.4.enemy.6.movementSpeed=6
wave.4.enemy.6.posX=520
wave.4.enemy.6.type=strafing
wave.4.enemy.7.arrivalTime=246
wave.4.enemy.7.movementSpeed=2
wave.4.enemy.7.posX=84
wave.4.enemy.7.type=shooting
wave.4.enemy.8.arrivalTime=246
wave.4.enemy.8.movementSpeed=5
wave.4.enemy.8.posX=301
wave.4.enemy.8.type=regular
wave.4.enemy.9.arrivalTime=246
wave.4.enemy.9.movementSpeed=4
wave.4.enemy.9.posX=486
wave.4.enemy.9.type=strafing
wave.4.enemy.10.arrivalTime=300
wave.4.enemy.10.movementSpeed=3
wave.4.enemy.10.posX=163
wave.4.enemy.10.type=shooting
wave.4.enemy.11.arrivalTime=333
wave.4.enemy.11.movementSpeed=6
wave.4.enemy.11.posX=372
wave.4.enemy.11.type=regular
wave.4.enemy.12.arrivalTime=333
wave.4.enemy.12.movementSpeed=1
wave.4.enemy.12.posX=507
wave.4.enemy.12.type=shooting
wave.4.enemy.13.arrivalTime=390
wave.4.enemy.13.movementSpeed=5
wave.4.enemy.13.posX=225
wave.4.enemy.13.type=strafing
wave.4.enemy.14.arrivalTime=438
wave.4.enemy.14.movementSpeed=2
wave.4.enemy.14.posX=117
wave.4.enemy.14.type=regular
wave.4.enemy.15.arrivalTime=438
wave.4.enemy.15.movementSpeed=4
wave.4.enemy.15.posX=312
wave.4.enemy.15.type=shooting
wave.4.enemy.16.arrivalTime=438
wave.4.enemy.16.movementSpeed=6
wave.4.enemy.16.posX=451
wave.4.enemy.16.type=strafing
wave.4.enemy.17.arrivalTime=492
wave.4.enemy.17.movementSpeed=3
wave.4.enemy.17.posX=266
wave.4.enemy.17.type=regular
wave.4.enemy.18.arrivalTime=534
wave.4.enemy.18.movementSpeed=5
wave.4.enemy.18.posX=389
wave.4.enemy.18.type=shooting
wave.4.enemy.19.arrivalTime=534
wave.4.enemy.19.movementSpeed=2
wave.4.enemy.19.posX=91
wave.4.enemy.19.type=strafing
wave.4.powerup.0.arrivalTime=180
wave.4.powerup.0.posX=142
wave.4.powerup.0.type=shield
wave.4.powerup.1.arrivalTime=360
wave.4.powerup.1.posX=326
wave.4.powerup.1.type=engine
wave.4.powerup.2.arrivalTime=540
wave.4.powerup.2.posX=471
wave.4.powerup.2.type=life

# Explosion settings
explosion.large.duration=30
explosion.large.image=res/explosionLarge.png
explosion.small.duration=20
explosion.small.image=res/explosionSmall.png

# Start screen settings
start.instructionsList.rowGap=30
start.instructionsList.startPosY=500
start.instructionsList.text=PRESS SPACE,TO START
start.title.posY=200
start.title.size=48
start.title.text=SHADOW ALIENS

# Pause screen settings
pausedTitle.text=GAME PAUSED
pausedTitle.size=48
pausedTitle.posY=300
controlsList.text=A/D KEYS TO MOVE,SPACEBAR TO SHOOT,G TO INCREASE SPEED,F TO DECREASE SPEED,I TO ENABLE INVINCIBLE MODE,ESC TO PAUSE/UNPAUSE,R TO RESTART GAME,N FOR NEXT WAVE
controlsList.startPosY=350
controlsList.rowGap=30
timescale.text=SPEED X
timescale.pos=450,800

# End screen settings
end.instructionsList.rowGap=30
end.instructionsList.startPosY=500
end.instructionsList.text=PRESS SPACE,TO PLAY AGAIN
end.lose.posY=200
end.lose.size=48
end.lose.text=GAME OVER
end.win.posY=200
end.win.size=48
end.win.text=VICTORY!